### ISSUE TITLE
Difficulties with module usage

### ISSUE THREAD

**Issue by kyrenya** [tripal/tripal_jbrowse#13]
hi! 
I have just download the tripal_jbrowse branch 7.x-3.x using git clone, 
but I cannot see the option JBrowse Instance in Add content menu. 
On the other hand, I see in my modules list, that I have in category Other, something called Hardwoods jbrowse: Create JBrowse instance. 
Shall I enable that and then go on following documentation? or in the other hand this is due to downloading a wrong version of this module? 

Thanks a lot in advance, 
Cirenia.

**Comment by almasaeed2010** [comment]
Hello @kyrenya 

Thanks for pointing out the issue! We are currently still in the process of merging the previously separate modules into one and missed changing the info for the module. I'll get that updated and get back to you soon.

Thanks!

**Comment by kyrenya** [comment]
ok! not at all, thanks to you for working in this! I'll stay tuned for updates! 
cheers!

**Comment by almasaeed2010** [comment]
Ok we have a quick fix that needs to be reviewed before we can merge. For the time being, if you'd like to test this module you can do the following:

- navigate to the module directory and run:
```
git pull
git checkout fix-hardwoods-references
```
- Follow the instructions in this [temporary documentation](https://hardwoods-jbrowse.readthedocs.io/en/latest/guide/installation.html) to learn about configuring, creating and managing jbrowse.

If you have any questions, please let us know. Thanks!

**Comment by kyrenya** [comment]
I'm afraid I cannot try right now because of bad news.. when enabling the tripal_jbrowse modules in the admin-modules site, when Saving changes.. the site got crashed, and now I cannot access anymore to the site... :S have you had that issue? any idea of what is happening?

**Comment by almasaeed2010** [comment]
Can you try to disable the module:

```
drush dis -y tripal_jbrowse tripal_jbrowse_mgmt
```

**Comment by kyrenya** [comment]
didnt work :(

**Comment by bradfordcondon** [comment]
did you get a drush error?  The module disabled successfully but no restoring your site? 

Please share errors so we can help.

**Comment by kyrenya** [comment]
exactly. Now I am trying drush pm-uninstall tripal_jbrowse and see what happens.

**Comment by kyrenya** [comment]
that worked! thanks!  I'll be out of work a couple of days.. as soon as I back I will try again the module.. and hope for the best! I will keep you updated! Thanks both!

**Comment by laceysanderson** [comment]
How did it go @kyrenya? Did the module work for you after this?

**Comment by kyrenya** [comment]
Yes, sorry, it worked fine!

**Comment by laceysanderson** [comment]
Great! I’m glad it worked! Let us know if you run into any more problems 🙂
