### ISSUE TITLE
confusion: jbrowse and jbrowse_mgmt BOTH have "create new jbrowse instance" forms

### ISSUE THREAD

**Issue by kyrenya** [tripal/tripal_jbrowse#19]
hi there! I'm trying to follow the documentation to create a new JBrowse instance, but I dont find where to indicate the Existing JBrowse URL as its said in the documentation https://tripal-jbrowse.readthedocs.io/en/latest/tripal_jbrowse/instance_page.html

this is the screen I see when trying to create the instance.
![image](https://user-images.githubusercontent.com/43243429/51192461-766a6000-18de-11e9-9c1d-8c9e81399e4a.png)

Any help? 
thanks in advance!

**Comment by laceysanderson** [comment]
Oh no, it doesn't seem to have created any of the fields it was supposed to on install. Can you try the following:
1. Disable and uninstall the module
2. Confirm the JBrowse instance content type is gone by going to content > add content
3. Clear the cache and re-enable the module

I'm traveling today but will look into it further tomorrow if the above instructions don't work. Thank you for the feedback!

**Comment by kyrenya** [comment]
ok no hurries! I'll try and keep you posted, and then we can figure it out when you are back! 
thanks!

**Comment by kyrenya** [comment]
I had no luck, we keep in touch once you are back! thx and have a nice trip!

**Comment by bradfordcondon** [comment]
I wasnt able to replicate this problem using a fresh site install.

![screen shot 2019-01-15 at 2 42 42 pm](https://user-images.githubusercontent.com/7063154/51205403-d4de1100-18d3-11e9-930e-968a5b1dee0b.png)


@kyrenya can you double check that you are using hte latest version of the `tripal_jbrowse` code ie `git pull` ?

if you run the command ` git log --pretty=format:'%h' -n 1` you should get `69bfbbd`:
```
 git log --pretty=format:'%h' -n 1
69bfbbd
```
(this confirms that the last change on yoru local copy matches the last change on github's master copy)

**Comment by kyrenya** [comment]
yep, got it! 
![image](https://user-images.githubusercontent.com/43243429/51243231-e4179a00-1979-11e9-9775-db93a2f3b26f.png)

**Comment by kyrenya** [comment]
just for checking a bit more in detail.. 
I see this in my modules list: 

![image](https://user-images.githubusercontent.com/43243429/51247760-044d5600-1986-11e9-9c63-981abbab5da5.png)


![image](https://user-images.githubusercontent.com/43243429/51247744-f8619400-1985-11e9-8afa-831fca05cb4e.png)

is it supposed to be like that? or only one module? which of those two is supposed to be enabled to create a new instance? (I think by now I've tried all the possible combinations... ).

Thanks again , 
Cirenia

**Comment by kyrenya** [comment]
still didnt manage to put this to work.. any advice?
Thanks!

**Comment by bradfordcondon** [comment]
did you try the steps @laceysanderson  suggested above?

>1. Disable and uninstall the module
>2. Confirm the JBrowse instance content type is gone by going to content > add content
>3. Clear the cache and re-enable the module

Given that I can't recreate the problem, this is a good place to start.

>is it supposed to be like that? or only one module? which of those two is supposed to be enabled to create a new instance? (I think by now I've tried all the possible combinations... ).

Yes thats what it should be.  the content "Jbrowse instance" content type is only managed by `tripal_jbrowse` and you only need that module installed.  Installing the management module won't affect this content type (i've confirmed this on my local site).

**Comment by kyrenya** [comment]
I think I have a clue now of what was wrong.. 
there were two paths for going to Create JBrowse Instance. 
If you do Tripal >> Extensions >> Tripal JBrowse Management >> Create JBrowse Instance: 
you get this: 
![image](https://user-images.githubusercontent.com/43243429/52214126-d4101d80-2888-11e9-9ceb-4dfac319535e.png)

Anyway, I was not getting the appropiate menu for the instance either that way, or via Add Content. 

I disabled, uninstalled and re-installed the module a couple of times. 
Now seems to work! Don't ask me why, I still dont know. The branch seems to be the same.. 
maybe cache issues? 
anyway, you can mark it as solved :) :) 

Thanks a lot as always.

**Comment by bradfordcondon** [comment]
of course, glad you got it working.

I think we need to do something to make this less confusing.  we can't have the Jbrowse Management module and the Jbrowse module both have a form to create a new Jbrowse Instance.  IE `node/add/jbrowse-instance` and `admin/tripal/extension/tripal_jbrowse/management/instances/add` should do something to distinguish what each "instance" is.  

As it is, each form says "add a new Jbrowse Instance"

**Comment by kyrenya** [comment]
cool thanks! :)

**Comment by laceysanderson** [comment]
There is now a plan for reducing this confusion which is described in full here: #25. To summarize, there will only be a single "Create JBrowse Instance" path which will be provided by "Tripal JBrowse Management".

I'm closing this issue in favour of #25. Please comment there with any suggestions/concerns!
