### ISSUE TITLE
Ensure page Query parameters are reflected in embedded JBrowse instance.

### ISSUE THREAD

**Issue by gdroc** [tripal/tripal_jbrowse#22]
I would like to suggest an improvement for the template node--jbrowse-instance.tpl.php to take into account the query parameter (location or tracks).
Thanks in advance
Gaetan

```php

<?php
  // Determine the URL of the JBrowse based on the node properties
  $url = $node->field_jburl['und'][0]['url'];
  $parts = array();
  //$parts['loc'] = (!empty($node->field_jbloc['und'][0])) ? 'loc='.$node->field_jbloc['und'][0]['safe_value'] : '';
  //$parts['tracks'] = (!empty($node->field_jbtracks['und'][0])) ? 'tracks='.$node->field_jbtracks['und'][0]['safe_value'] : '';
  $parts['data'] = (!empty($node->field_datadir['und'][0])) ? 'data='.$node->field_datadir['und'][0]['safe_value'] : '';
  
  // Get query parameters
  $params = drupal_get_query_parameters();
  $loc = ''; 
  $tracks = array();
  $query_tracks = array();
  $default_tracks = array();
  
  // Case for loc parameters
  if (isset($params['loc'])) {
    $parts['loc'] = 'loc='.$params['loc'];
    unset($params['loc']);
  }
  elseif (!empty($node->field_jbloc['und'][0])) {
    $parts['loc'] = 'loc='.$node->field_jbloc['und'][0]['safe_value'];
  }
    
  if (!empty($node->field_jbtracks['und'][0])){ 
    $default_tracks = explode("," , $node->field_jbtracks['und'][0]['safe_value']) ; 
  }
  // Case for tracks parameters
  if (isset($params['tracks'])) {
    $query_tracks = explode("," , $params['tracks']) ; 
    unset($params['tracks']);
  }
  // Merge array for tracks param
  $tracks = array_unique (array_merge ($default_tracks, $query_tracks));
  
  $parts['tracks'] = 'tracks='.implode(',',$tracks); 
  
  // Case for all other parameters
  foreach ($params as $key => $value) {
    $parts[$key] = $key ."=". rawurlencode($value);
  }
  // Reconstruct URL
  if ($parts) {
    $url = "$url/?" . implode('&', $parts);
  } 
?>
```

**Comment by laceysanderson** [comment]
Hi @gdroc, this looks like a great contribution. Would you like to make a pull request for it so you get credit?

**Comment by gdroc** [comment]
Hi @laceysanderson, yes it's great idea If you explain me how to do that. Probably, @guignonv can also help me to do that.

**Comment by guignonv** [comment]
Sure @gdroc!
Let's talk about it next time we meet! (next Thursday I think or before)

**Comment by laceysanderson** [comment]
Hi @gdroc, this module is moving away from nodes for the embedded page as stated in #26. I will incorporate this suggestion into the new Tripal JBrowse page integration module, give you credit and provide an upgrade path for existing users :-)

**Comment by laceysanderson** [comment]
This suggestion has been committed into the [new tripal_jbrowse_page module within this repo](https://github.com/tripal/tripal_jbrowse/tree/page-integration-v2) which is almost ready for use. The current tripal_jbrowse module is being deprecated as mentioned above. As such I'm closing this issue.

Thank you for the suggestion @gdroc!
