### ISSUE TITLE
Slight iteration on the README docs needed?

### ISSUE THREAD

**Issue by RichardBruskiewich** [tripal/tripal_jbrowse#3]
I'm told through the grapevine that the Drupal Link module is already integrated with Tripal v3.x.

Perhaps this fact can be noted in the README for tripal_jbrowse, so that the uninitiated users of this module don't panic about installing Link?

**Comment by laceysanderson** [comment]
Thanks for the feedback! I have added that to the new documentation (not quite merged) to make it more clear :-)
