### ISSUE TITLE
Create Symbolic link as copy of upload file

### ISSUE THREAD

**Issue by Jiu9Shen** [tripal/tripal_jbrowse#33]
A copy of upload file will be saved in `your_site/tools/jbrowse/data/your_instance/data` when a instance or a track is added using tripal_jbrowse. 
The issue related is that all the copies can use too much storage space on server, specially for large files. One solution for this issue is creating symbolic links rather than actual copies. 

To deal with this issue, I would like to make some changes in this module. My plan is creating a Fork of tripal_jbrowse in my account and send back for review when ready.

**Comment by laceysanderson** [comment]
PR Merged
