### ISSUE TITLE
Allow multiple JBrowses for one Organism

### ISSUE THREAD

**Issue by Jiu9Shen** [tripal/tripal_jbrowse#35]
![Screenshot from 2019-12-03 10-35-16](https://user-images.githubusercontent.com/26550071/70070147-b8fd5f80-15b8-11ea-8665-da3e9a3d946d.png)

It is common that one organism has multiple versions of genome, so it will be nice if tripal_jbrowse can be compatible with it.

**Comment by laceysanderson** [comment]
I think the most generic, backwards compatible way to add this functionality is make the combination of analysis/organism unique. This way different assemblies and/or different source germplasm can be indicated through an analysis record. Specifically,

1. Add analysis_id foreign key to `tripal_jbrowse_mgmt_instances` table and ensure it is optional.
2. Change unique checking to check the combination of analysis/organism. If there is no analysis specified it will be backwards compatible and specific to the organism.

Note: make sure this change is backwards compatible!

**Comment by laceysanderson** [comment]
Merged! Thank you @Jiu9Shen
