### ISSUE TITLE
Error found in Instance Edit page

### ISSUE THREAD

**Issue by Jiu9Shen** [tripal/tripal_jbrowse#49]
![Screenshot from 2020-02-19 10-42-23](https://user-images.githubusercontent.com/26550071/74854188-9ac81580-5304-11ea-9f7d-8ccbc913470e.png)
Found error while making changes in INSTANCE PAGE SETTINGS(Start Location, Tracks to Display) in instance edit page. 

Also, this error doesn't alway occur while editing instance settings.

**Comment by laceysanderson** [comment]
I'm unable to duplicate this. I've tried on multiple development sites as well as our production. I've also tried every combination of filling out fields and re-editing I could think of 🤷‍♀. As such, I'm going to close the issue

**BUT if you experience this again using the most recent development version and can suggest steps to reproduce, please comment here and I will re-open!**
