### ISSUE TITLE
The data directory is not writeable.

### ISSUE THREAD

**Issue by elor77** [tripal/tripal_jbrowse#56]
@laceysanderson 
When trying to save the settings of the Tripal Jbrowse Managment, I get the following error

`The data directory is not writeable`

Even though the directory is. (I did chmod 777 on all)

Any ideas?

**Comment by bradfordcondon** [comment]
what path are you entering for the data directory configuration? The path you are feeding it is failing this check:

`  elseif (!is_writable($values['data_dir']) || !is_dir($values['data_dir'])) {`

**Comment by elor77** [comment]
I'm using this path: /var/www/html/tools/jbrowse/data

**Comment by bradfordcondon** [comment]
OK, so what is the output of `ls -alF  /var/www/html/tools/jbrowse/`. Most likely it is a permission issue but lets also double check the path is right

**Comment by elor77** [comment]
I also think it's a permission issue, was hoping granting `all` writing permission would overcome that.   (I´m new to the whole drupal / tripal env - your docs are very helpful - thanks for that) 
Here´s the output:
```
total 2288
drwxrwxrwx. 11 ofirt ofirt    4096 Mar 20 15:24 ./
drwxrwxrwx.  3 ofirt ofirt      21 Mar 20 13:57 ../
drwxrwxrwx.  2 ofirt ofirt    4096 Feb  5 04:18 bin/
-rwxrwxrwx.  1 ofirt ofirt     258 Feb  5 04:18 browserconfig.xml*
-rwxrwxrwx.  1 ofirt ofirt    3385 Feb  5 04:18 CODE_OF_CONDUCT.md*
drwxrwxrwx.  2 ofirt ofirt       6 Mar 20 15:24 data/
drwxrwxrwx.  3 ofirt ofirt     141 Feb  5 04:19 dist/
drwxrwxrwx.  5 ofirt ofirt      50 Feb  5 04:18 docs/
drwxrwxrwx.  5 ofirt ofirt      39 Mar 20 14:27 extlib/
drwxrwxrwx.  3 ofirt ofirt    4096 Feb  5 04:18 img/
-rwxrwxrwx.  1 ofirt ofirt    1575 Feb  5 04:18 index.html*
-rwxrwxrwx.  1 ofirt ofirt      97 Feb  5 04:18 INSTALL*
-rwxrwxrwx.  1 ofirt ofirt    3045 Feb  5 04:18 jbrowse.conf*
-rwxrwxrwx.  1 ofirt ofirt     299 Feb  5 04:18 jbrowse_conf.json*
-rwxrwxrwx.  1 ofirt ofirt   33634 Feb  5 04:18 LICENSE*
-rwxrwxrwx.  1 ofirt ofirt   60293 Mar 20 14:33 Makefile*
-rwxrwxrwx.  1 ofirt ofirt    2946 Feb  5 04:18 Makefile.PL*
-rwxrwxrwx.  1 ofirt ofirt    2679 Mar 20 14:33 MYMETA.json*
-rwxrwxrwx.  1 ofirt ofirt    1591 Mar 20 14:33 MYMETA.yml*
-rwxrwxrwx.  1 ofirt ofirt    3399 Feb  5 04:18 package.json*
drwxrwxrwx.  8 ofirt ofirt     144 Feb  5 04:18 plugins/
-rwxrwxrwx.  1 ofirt ofirt    4668 Feb  5 04:18 README.md*
-rwxrwxrwx.  1 ofirt ofirt  170057 Feb  5 04:18 release-notes.md*
drwxrwxrwx.  4 ofirt ofirt      54 Feb  5 04:18 sample_data/
-rwxrwxrwx.  1 ofirt ofirt 1638030 Mar 20 14:33 setup.log*
-rwxrwxrwx.  1 ofirt ofirt   10272 Feb  5 04:18 setup.sh*
-rwxrwxrwx.  1 ofirt ofirt     464 Feb  5 04:18 site.webmanifest*
drwxrwxrwx.  3 ofirt ofirt      19 Feb  5 04:19 src/
-rwxrwxrwx.  1 ofirt ofirt    3995 Feb  5 04:18 webpack.config.js*
-rwxrwxrwx.  1 ofirt ofirt  346055 Feb  5 04:18 yarn.lock*

```

**Comment by bradfordcondon** [comment]
ok so it exists, youre providing the full and not the relative path, and it should be writable, so its a permission issue.  `chmod -R 777` isn't really a great solution.  The exact solution is going to depend on your server setup.  You can take a look in your Drupal files folder to get a sense for what they should be.  (`[tripal site root]/sites/default/files`).  For me, my writable directories need to be owned by `_www` as thats the user when my server runs Drupal: `chown -R _www:staff`



if you arent sure what system user Drupal is when its executing PHP, if you have [the `devel` module enabled](https://www.drupal.org/project/devel), you can go to `http://[drupalSite]/devel/php` and run this line of code: `dpm(posix_getpwuid(posix_geteuid())['name']);`

**Comment by elor77** [comment]
Turns out on CentOS there's another security layer - had do deactivate it by using 
`sudo setenforce 0`
found the answer here : https://www.drupal.org/forum/support/installing-drupal/2018-02-13/solved-the-directory-sitesdefaultfiles-is-not-writable
Thank you very much for your assistance!
