### ISSUE TITLE
Unable to edit JBrowse instance when there is more than one JBrowse for an organism of the same species

### ISSUE THREAD

**Issue by carolyncaron** [tripal/tripal_jbrowse#65]
I have 2 JBrowses for the same organism; one for an older version of the genome and a recently added one with an updated genome assembly. I'd like to change the description for the newest one (by going to Admin menu -> Tripal -> Extensions -> Tripal JBrowse Management -> my instance I want to change -> Edit Instance) but whenever I click on Save Changes, the Organism field is highlighted red and I get the following error at the top of the page: 

> A JBrowse instance for the selected organism already exists. You can edit the instance from the instances page.

This occurs on the latest version of this module from Github (commit https://github.com/tripal/tripal_jbrowse/commit/4a8bbd8e6b74f7d1d0a6eeca7821765346abf78f)

**Comment by laceysanderson** [comment]
This was fixed by the linked PR.
