### ISSUE TITLE
Automated testing is broken due to multi-schema querying bug in Drupal 7

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal_jbrowse#74]
This is the exact same issue as tripal issue https://github.com/tripal/tripal/issues/1281 but the solution will need to be in https://github.com/tripal/setup-tripal-action

**Comment by dsenalik** [comment]
Relevant pull request in that module can be found at
https://github.com/tripal/setup-tripal-action/pull/2

**Comment by laceysanderson** [comment]
This was fixed by #75
